services:
    scim: true
    proxy: true
    ssf: true
redis:
    address: localhost:6379
    # address: redis-scim:6379
    password: ""
    db: 0
server:
    address: ":8082"
    web_address: ":8080"
    web_console: true
    debug_headers: false
    debug_body: false
    debug_query: false
    log_messages: false
    proxy_messages: false
    proxy_address: ":8084"
    filter_ips: true
    okta_public_ips_url: "https://s3.amazonaws.com/okta-ip-ranges/ip_ranges.json"
scim:
    enable_groups: true
    users_endpoint: "/goscim/scim/v2/Users"
    groups_endpoint: "/goscim/scim/v2/Groups"
build: "v1.22.001"